### ISSUE TITLE
Update RTD config file

### ISSUE THREAD

**Issue by FromenActual** [FTC-Goodies/All-Goodies#3]
https://blog.readthedocs.com/migrate-configuration-v2/

**Comment by ramalamadingdong** [comment]
Took a few tries but hey it's good now, we won't get annoying emails :D

**Comment by ramalamadingdong** [comment]
We should consider adding the requirements.txt for when we inevitably add some cool library

**Comment by FromenActual** [comment]
Thanks for doing this!
